### ISSUE TITLE
using EPD-Analyzer to blundercheck repertoire for white or for black

### ISSUE THREAD

**Issue by Jonathan003** [fsmosca/EPD-Analyzer#10]
Could the the EPD-Analysing tool be used to blunder check my white repertoire for example?
And if I have my repertoire in pgn format (single games for each opening lines), what would be the best way to convert it to epd to be able to use is with the EPD-Analyzer tool.
I could blundercheck only the white moves from the repertoire in pgn, with Fritz or Scid vs PC.
But I want to avoid that an engine has to go over the same opening lines again and again.

**Comment by fsmosca** [comment]
This tool is not used for blunder checking.
