### ISSUE TITLE
the [event] tag to count the FENs in order

### ISSUE THREAD

**Issue by ChessOTB** [fsmosca/EPD-Analyzer#4]
Thank you very much for making such a great app!

Could you, please, make that inside the output PGN, the [event] tag (or other) would count the FENs in their order of appearance? This is useful if, for example, you analyze an EPD from a book of puzzles, to have the solutions corresponding the exercise number (more or less). Also it helps identify a wrong FEN inside the EPD.

**Comment by fsmosca** [comment]
Try v0.18.beta python source. The output would look like this.

```
[Event "Position no. 1"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "1-0"]
[AnalysisMovetimeMs "1000"]
[Annotator "Stockfish 11 64 POPCNT"]
[CentipawnEvaluation "31998"]
[EPDId "WAC.001"]
[FEN "2rr3k/pp3pp1/1nnqbN1p/3pN3/2pP4/2P3Q1/PPB4P/R4RK1 w - - 0 1"]
[SetUp "1"]

1. Qg6 Nxe5 2. Qh7# 1-0
```

**Comment by ChessOTB** [comment]
Looking forward for the new release... Thank you!

**Comment by fsmosca** [comment]
v0.20.beta is released with this modification.

**Comment by fsmosca** [comment]
Closed by https://github.com/fsmosca/EPD-Analyzer/commit/9315eeb94c99cc724aa44a48fc90234fa8247b09
