### ISSUE TITLE
minimum number of moves to display for the pv

### ISSUE THREAD

**Issue by ChessOTB** [fsmosca/EPD-Analyzer#5]
Is it possible to tell Stockfish to display a minimum number of moves for the predicted variation?
It happens sometimes it gives only one move even the engine run 1 minute per position to analyze.

**Comment by fsmosca** [comment]
Stockfish has no option to control the number of moves in the pv.

What I can do is to extend the search and once there are more moves in the pv, I will stop the search. The other option is to save the previous pv, if the current pv has a single move, check the previous pv, if there are more moves there, use that pv instead but this has the danger of not saving the best pv.

I will add the search extension and make this as a flag.
`--extend-search`
By default, this is off.

Sample with added opcode Aacms (Actual analysis count: milliseconds). Note the engine is set to limit its search at 1000ms, after 1000ms I check the pv length, if more than 1, I stop the search.

```
2rr3k/pp3pp1/1nnqbN1p/3pN3/2pP4/2P3Q1/PPB4P/R4RK1 w - - acd 245; acs 1; ce 31998; dm 2; id "WAC.001"; pm Qg6; pv Qg6 Nxe5 Qh7#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 181;
8/7p/5k2/5p2/p1p2P2/Pr1pPK2/1P1R3P/8 b - - acd 23; acs 1; ce 803; id "WAC.002"; pm Rxb2; pv Rxb2 Rxb2 c3 Rb6+ Ke7 Rc6 c2 Kg3 Kd7 Rc3 d2 Rxc2 d1=Q Rg2 Qc1 Ra2 Qg1+ Kf3 Qd1+ Re2 Kd6 h4 Qd3 Kf2 Qxa3 e4 fxe4 Rxe4 Qc5+ Kg3 a3 Ra4 Qg1+ Kf3 Qf1+ Ke4; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 2265;
5rk1/1ppb3p/p1pb4/6q1/3P1p1r/2P1R2P/PP1BQ1P1/5RKN w - - acd 23; acs 1; ce 598; id "WAC.003"; pm Rg3; pv Rg3 Bg4 Rxg4 Rxg4 Qxg4 Qxg4 hxg4 c5 Kf2 cxd4 cxd4 Rd8 Ke2 Rd7 Rf3 Bf8 Rxf4 Bh6 Re4 Bxd2 Kxd2 c5 Nf2 Rxd4+ Rxd4 cxd4 Kd3 Kg7 Kxd4 Kg6 Kc5 h5 gxh5+ Kxh5 Kb6 Kg5; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 1056;
r1bq2rk/pp3pbp/2p1p1pQ/7P/3P4/2PB1N2/PP3PPR/2KR4 w - - acd 245; acs 1; ce 31998; dm 2; id "WAC.004"; pm Qxh7+; pv Qxh7+ Kxh7 hxg6#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 107;
5k2/6pp/p1qN4/1p1p4/3P4/2PKP2Q/PP3r2/3R4 b - - acd 245; acs 1; ce 31998; dm 2; id "WAC.005"; pm Qc4+; pv Qc4+ Nxc4 bxc4#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 105;
7k/p7/1R5K/6r1/6p1/6P1/8/8 w - - acd 50; acs 1; ce 31989; dm 11; id "WAC.006"; pm Rb7; pv Rb7 Kg8 Kxg5 Kf8 Rxa7 Ke8 Kxg4 Kd8 Kf5 Kc8 Rf7 Kd8 Ke6 Kc8 Kd6 Kb8 Kc6 Ka8 Kb6 Kb8 Rf8#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 4002;
rnbqkb1r/pppp1ppp/8/4P3/6n1/7P/PPPNPPP1/R1BQKBNR b KQkq - acd 18; acs 1; ce 816; id "WAC.007"; pm Ne3; pv Ne3 Ngf3 Nxd1 Kxd1 d6 e4 g6 exd6 Qxd6 Ke1 Bg7 h4 Qe7 Bd3 Bg4 c3 Nd7 Nb3 O-O Bc2 Nc5 Nxc5; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 1149;
r4q1k/p2bR1rp/2p2Q1N/5p2/5p2/2P5/PP3PPP/R5K1 w - - acd 57; acs 1; ce 31993; dm 7; id "WAC.008"; pm Rf7; pv Rf7 Qxf7 Nxf7+ Kg8 Nh6+ Kh8 Re1 Re8 Rxe8+ Bxe8 Qf8+ Rg8 Qxg8#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 4002;
3q1rk1/p4pp1/2pb3p/3p4/6Pr/1PNQ4/P1PB1PP1/4RRK1 b - - acd 81; acs 1; ce 31995; dm 5; id "WAC.009"; pm Bh2+; pv Bh2+ Kh1 Bg3+ Kg1 Rh1+ Kxh1 Qh4+ Kg1 Qh2#; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 4001;
2br2k1/2q3rn/p2NppQ1/2p1P3/Pp5R/4P3/1P3PPP/3R2K1 w - - acd 22; acs 1; ce 722; id "WAC.010"; pm Rxh7; pv Rxh7 a5 Rxg7+ Qxg7 Qxg7+ Kxg7 Nf5+ exf5 Rxd8 Be6 Rd6 Bb3 exf6+ Kg6 Ra6 c4 Rxa5 c3 bxc3 bxc3 f7 Kxf7 Rxf5+ Ke6 Rc5 Ba2 Rxc3 Kd6 a5 Kd5; Anno "Stockfish 11 64 POPCNT"; Acms 1000; Aacms 1024;
```

**Comment by fsmosca** [comment]
v0.20.beta is released with this modification.

**Comment by ChessOTB** [comment]
Indeed it fixes the SF issue, however running any other engine without the new flag increases the total running time about 3 times. For example, Lc0, on the standard test (MTMS=1000 and wacnew.epd file), requires 16 minutes to finish it while only 6 minutes if added the flag. Therefore the "extend search" flag becomes mandatory for any engine that was not requiring before such a fix. The question is if the quality of analysis is not diminished for those engines. As I understand from the explanation on first post, with this flag we still obtain the best pv. Then maybe the flag can be included inside the eap capsule as general for any engine to run.

**Comment by fsmosca** [comment]
I see the bug now. Will release a fix later.

**Comment by fsmosca** [comment]
Fixed in https://github.com/fsmosca/EPD-Analyzer/commit/3beb2358dae3d9f5d040b7b6b84e3c66e8363a8b
