### ISSUE TITLE
Combine depth and time don't work

### ISSUE THREAD

**Issue by Jonathan003** [fsmosca/EPD-Analyzer#9]
I have downloaded v0.21
If I use this this script `eap --input outB.epd --engine-name "Stockfish 13" --engine SF13.exe --engine-option "Hash=1024, Threads=4" --movetimems 1000 --outputpgn sfpgnoutput.pgn`
It works.
But I I try this script `eap --input outB.epd --engine-name "Stockfish 13" --engine SF13.exe --engine-option "Hash=1024, Threads=4" --depth 14 --movetimems 1000 --outputpgn sfpgnoutput.pgn`
I fails and I get the error message: EAP - EPD Analysis to PGN v0.21.beta: error: unrecognized arguments: --depth 14

**Comment by fsmosca** [comment]
0.21 does not support --depth.

The new eap.py supports --depth.
